# Generated by Django 6.0.1 on 2026-01-29 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
