# Generated by Django 6.0.1 on 2026-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0002_alter_maqola_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
