# Generated by Django 6.0.1 on 2026-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0003_alter_maqola_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='adminReply',
            field=models.CharField(blank=True, null=True),
        ),
    ]
