# Generated by Django 6.0.1 on 2026-01-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maqola', '0004_alter_comment_adminreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='salom'),
            preserve_default=False,
        ),
    ]
